Repository measure-sh/measure, pull requests merged in 2024-08, with the labels that each got.

#1067 fix(android): resolve crash when OkHttp is not a runtime dependency
  android/measure/consumer-rules.pro
  android/measure/src/androidTest/java/sh/measure/android/TestMeasureInitializer.kt
  android/measure/src/main/java/sh/measure/android/Measure.kt
  android/measure/src/main/java/sh/measure/android/MeasureInitializer.kt
  android/measure/src/main/java/sh/measure/android/MeasureInternal.kt
  android/measure/src/main/java/sh/measure/android/okhttp/HttpEventCollector.kt
  android/measure/src/main/java/sh/measure/android/okhttp/HttpEventCollectorFactory.kt
  android/measure/src/main/java/sh/measure/android/okhttp/OkHttpEventCollector.kt
Labels: bug

#1087 feat(android): apply bytecode transformation only for supported dependency versions
  android/measure-android-gradle/src/main/kotlin/sh/measure/DependencyUtils.kt
  android/measure-android-gradle/src/main/kotlin/sh/measure/MeasurePlugin.kt
  android/measure-android-gradle/src/main/kotlin/sh/measure/SemVer.kt
  android/measure-android-gradle/src/main/kotlin/sh/measure/asm/AsmBytecodeTransformer.kt
  android/measure-android-gradle/src/main/kotlin/sh/measure/asm/BytecodeTransformationPipeline.kt
  android/measure-android-gradle/src/main/kotlin/sh/measure/asm/BytecodeTransformationPipelineBuilder.kt
  android/measure-android-gradle/src/main/kotlin/sh/measure/asm/BytecodeTransformer.kt
  android/measure-android-gradle/src/main/kotlin/sh/measure/asm/ModuleInfo.kt
  android/measure-android-gradle/src/main/kotlin/sh/measure/asm/NavigationTransformer.kt
  android/measure-android-gradle/src/main/kotlin/sh/measure/asm/OkHttpTransformer.kt
  android/measure-android-gradle/src/main/kotlin/sh/measure/asm/TransformerParameters.kt
  android/measure-android-gradle/src/main/kotlin/sh/measure/asm/VersionAwareVisitor.kt
  docs/android/features/feature_navigation_and_lifecycle.md
  docs/android/gradle-plugin.md
Labels: gradle-plugin, feature

#1088 chore(android): fix publish command for gradle plugin on CI
  .github/workflows/android.yml
Labels: gradle-plugin

#1094 docs: fix formatting
  docs/hosting/README.md
Labels: docs

#1103 ci: fix git push
  .github/workflows/changelog.yml
Labels: bug

#1104 ci: fix git push
  .github/workflows/changelog.yml
Labels: chore

#1111 ci: update secret for git push of auto generated changelog
  .github/workflows/changelog.yml
Labels: chore

#1119 Ios sdk initialization
  ios/MeasureDemo/MeasureDemo.xcodeproj/project.pbxproj
  ios/MeasureDemo/MeasureDemo/AppDelegate.swift
  ios/MeasureDemo/MeasureDemo/MeasureDemo-Bridging-Header.h
  ios/MeasureDemo/MeasureDemo/MeasureManager.h
  ios/MeasureDemo/MeasureDemo/MeasureManager.m
  ios/MeasureSDK/MeasureSDK.xcodeproj/project.pbxproj
  ios/MeasureSDK/MeasureSDK/Config/BaseConfigProvider.swift
  ios/MeasureSDK/MeasureSDK/Config/Config.swift
  ios/MeasureSDK/MeasureSDK/Config/ConfigLoader.swift
  ios/MeasureSDK/MeasureSDK/Config/DefaultConfig.swift
  ios/MeasureSDK/MeasureSDK/Config/InternalConfig.swift
  ios/MeasureSDK/MeasureSDK/Config/Measure.swift
  ios/MeasureSDK/MeasureSDK/Config/MeasureConfig.swift
  ios/MeasureSDK/MeasureSDK/Measure.swift
  ios/MeasureSDK/MeasureSDK/MeasureInitializer.swift
  ios/MeasureSDK/MeasureSDK/MeasureInternal.swift
Labels: ios

#1152 docs: add specific types to numbers in SDK API docs
  docs/api/sdk/README.md
Labels: docs

#1155 chore(backend): reorder & cleanup postgres migrations
  self-host/postgres/20231117011737_create_roles_table.sql
  self-host/postgres/20240830075257_create_roles_table.sql
  self-host/postgres/20240830080137_create_users_table.sql
  self-host/postgres/20240830080707_create_teams_table.sql
  self-host/postgres/20240830081828_create_apps_table.sql.sql
  self-host/postgres/20240830081908_create_team_membership_table.sql
  self-host/postgres/20240830082904_create_api_keys_table.sql
  self-host/postgres/20240830083150_create_build_mappings_table.sql
  self-host/postgres/20240830083238_create_build_sizes_table.sql
  self-host/postgres/20240830083450_create_unhandled_exception_groups_table.sql
  self-host/postgres/20240830083536_create_anr_groups_table.sql
  self-host/postgres/20240830083705_create_event_reqs_table.sql
  self-host/postgres/20240830083806_create_alert_prefs_table.sql
  self-host/postgres/20240830083926_create_auth_sessions_table.sql
  self-host/postgres/20240830084037_create_auth_states_table.sql
  self-host/postgres/20240830084124_create_app_settings_table.sql
Labels: chore, backend
